# Generated by Django 4.2.1 on 2023-05-19 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20201219_2331"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uid", models.CharField(default=uuid.uuid4, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="game_opponent",
        ),
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(to="home.profile"),
        ),
    ]
