# Generated by Django 4.2.1 on 2023-05-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_game_is_in_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="room_code",
            field=models.CharField(default="5f3a4f5", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(default="ae8f5e7", max_length=20, unique=True),
        ),
    ]
