# Generated by Django 4.2.1 on 2023-05-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_game_room_code_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="room_code",
            field=models.CharField(default="dfc8d38", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(default="b4edf04", max_length=20, unique=True),
        ),
    ]
