# Generated by Django 4.2.1 on 2023-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_game_room_code_alter_profile_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="folded_cards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="game_score",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="unfolded_cards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="cards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="room_code",
            field=models.CharField(default="af83dc5", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(default="ce24210", max_length=20, unique=True),
        ),
    ]
